server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticationFilter
        - id: document-ingestion-service
          uri: lb://document-ingestion-service
          predicates:
            - Path=/api/docs/**
          filters:
            - AuthenticationFilter
    loadbalancer:
      ribbon:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://user-service:9092/oauth2/jwks
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true